# Generated by Django 5.2.7 on 2025-10-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
