# Generated by Django 5.2.7 on 2025-12-06 20:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_document_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default capabilities', max_length=100)),
                ('tech_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Technologies/stacks we are strong at.', size=None)),
                ('min_budget', models.PositiveIntegerField()),
                ('max_budget', models.PositiveIntegerField()),
                ('min_timeline_weeks', models.PositiveIntegerField()),
                ('max_timeline_weeks', models.PositiveIntegerField()),
                ('max_team_size', models.PositiveIntegerField()),
                ('max_parallel_projects', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='rfp_budget',
            field=models.PositiveIntegerField(blank=True, help_text='Expected project budget in INR (e.g. 800000 for ₹8L)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rfp_team_size_required',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people required by client', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rfp_timeline_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Expected duration in weeks', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVIEW', 'Needs Review')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='RFPEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_fit_score', models.FloatField(default=0.0)),
                ('budget_fit_score', models.FloatField(default=0.0)),
                ('timeline_fit_score', models.FloatField(default=0.0)),
                ('capacity_fit_score', models.FloatField(default=0.0)),
                ('overall_fit_score', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('REVIEW', 'Review')], default='REVIEW', max_length=10)),
                ('reasoning', models.TextField(blank=True, help_text='Short explanation of why this decision was taken.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='generation.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
