# Generated by Django 5.2.7 on 2025-12-10 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_companycapability_document_rfp_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycapability',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companycapability',
            name='name',
        ),
        migrations.AddField(
            model_name='companycapability',
            name='confidence',
            field=models.CharField(default='high', help_text='Internal evaluation confidence', max_length=10),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='expected_budget_in_inr',
            field=models.PositiveIntegerField(blank=True, help_text='Expected/typical project budget in INR', null=True),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='expected_emd_in_inr',
            field=models.PositiveIntegerField(blank=True, help_text='Expected EMD range for projects (INR)', null=True),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='expected_no_of_days_for_analysis',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='expected_no_of_days_for_submission',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='expected_team_size_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='expected_timeline_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Expected timeline for typical projects in weeks', null=True),
        ),
        migrations.AddField(
            model_name='companycapability',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_confidence',
            field=models.CharField(blank=True, help_text='Confidence level reported by extractor (high|medium|low)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_notes',
            field=models.TextField(blank=True, help_text='Short notes from metadata extractor', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='no_of_days_for_analysis',
            field=models.PositiveIntegerField(blank=True, help_text='No. of days allocated for analysis (if mentioned)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='no_of_days_for_submission',
            field=models.PositiveIntegerField(blank=True, help_text='No. of days allowed for submission (if mentioned)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rfp_emd',
            field=models.PositiveIntegerField(blank=True, help_text='Earnest Money Deposit (EMD) in INR if present in RFP', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rfp_metadata',
            field=models.JSONField(blank=True, help_text='Raw extracted RFP metadata JSON (from Gemini)', null=True),
        ),
        migrations.AlterField(
            model_name='companycapability',
            name='tech_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
