# Generated by Django 5.2.7 on 2025-12-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_remove_companycapability_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycapability',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='companycapability',
            name='expected_budget_in_inr',
        ),
        migrations.RemoveField(
            model_name='companycapability',
            name='expected_team_size_required',
        ),
        migrations.RemoveField(
            model_name='companycapability',
            name='max_parallel_projects',
        ),
        migrations.RemoveField(
            model_name='companycapability',
            name='notes',
        ),
    ]
